/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ExpiringRouteImport } from './routes/expiring'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as HowDiscountsRouteImport } from './routes/how-discounts'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VendorSignupRouteImport } from './routes/vendor-signup'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as AuthenticatedBrandRouteImport } from './routes/_authenticated/brand'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSavingsRouteImport } from './routes/_authenticated/savings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as BundleIdRouteImport } from './routes/bundle.$id'
import { Route as PaymentOrderIdRouteImport } from './routes/payment.$orderId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as VendorSlugRouteImport } from './routes/vendor.$slug'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders_.$id'
import { Route as AuthenticatedProfileAddressesRouteImport } from './routes/_authenticated/profile_.addresses'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile_.edit'
import { Route as AuthenticatedProfileWalletRouteImport } from './routes/_authenticated/profile_.wallet'
import { Route as ApiPublicQiWebhookRouteImport } from './routes/api/public/qi-webhook'
import { Route as AuthenticatedProfileWalletStatementRouteImport } from './routes/_authenticated/profile_.wallet_.statement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiringRoute = ExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const HowDiscountsRoute = HowDiscountsRouteImport.update({
  id: '/how-discounts',
  path: '/how-discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSignupRoute = VendorSignupRouteImport.update({
  id: '/vendor-signup',
  path: '/vendor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrandRoute = AuthenticatedBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavingsRoute = AuthenticatedSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleIdRoute = BundleIdRouteImport.update({
  id: '/bundle/$id',
  path: '/bundle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOrderIdRoute = PaymentOrderIdRouteImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSlugRoute = VendorSlugRouteImport.update({
  id: '/vendor/$slug',
  path: '/vendor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileAddressesRoute =
  AuthenticatedProfileAddressesRouteImport.update({
    id: '/profile_/addresses',
    path: '/profile/addresses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile_/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileWalletRoute =
  AuthenticatedProfileWalletRouteImport.update({
    id: '/profile_/wallet',
    path: '/profile/wallet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicQiWebhookRoute = ApiPublicQiWebhookRouteImport.update({
  id: '/api/public/qi-webhook',
  path: '/api/public/qi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileWalletStatementRoute =
  AuthenticatedProfileWalletStatementRouteImport.update({
    id: '/profile_/wallet_/statement',
    path: '/profile/wallet/statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/deals': typeof DealsRoute
  '/expiring': typeof ExpiringRoute
  '/featured': typeof FeaturedRoute
  '/how-discounts': typeof HowDiscountsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/outlet': typeof OutletRoute
  '/products': typeof ProductsRoute
  '/rewards': typeof RewardsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/vendors': typeof VendorsRoute
  '/brand': typeof AuthenticatedBrandRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/savings': typeof AuthenticatedSavingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/bundle/$id': typeof BundleIdRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/profile/addresses': typeof AuthenticatedProfileAddressesRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/wallet': typeof AuthenticatedProfileWalletRoute
  '/api/public/qi-webhook': typeof ApiPublicQiWebhookRoute
  '/profile/wallet/statement': typeof AuthenticatedProfileWalletStatementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/deals': typeof DealsRoute
  '/expiring': typeof ExpiringRoute
  '/featured': typeof FeaturedRoute
  '/how-discounts': typeof HowDiscountsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/outlet': typeof OutletRoute
  '/products': typeof ProductsRoute
  '/rewards': typeof RewardsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/vendors': typeof VendorsRoute
  '/brand': typeof AuthenticatedBrandRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/savings': typeof AuthenticatedSavingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/bundle/$id': typeof BundleIdRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/admin': typeof AdminIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/profile/addresses': typeof AuthenticatedProfileAddressesRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/wallet': typeof AuthenticatedProfileWalletRoute
  '/api/public/qi-webhook': typeof ApiPublicQiWebhookRoute
  '/profile/wallet/statement': typeof AuthenticatedProfileWalletStatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/deals': typeof DealsRoute
  '/expiring': typeof ExpiringRoute
  '/featured': typeof FeaturedRoute
  '/how-discounts': typeof HowDiscountsRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/outlet': typeof OutletRoute
  '/products': typeof ProductsRoute
  '/rewards': typeof RewardsRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/vendors': typeof VendorsRoute
  '/_authenticated/brand': typeof AuthenticatedBrandRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/savings': typeof AuthenticatedSavingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/bundle/$id': typeof BundleIdRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/orders_/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/profile_/addresses': typeof AuthenticatedProfileAddressesRoute
  '/_authenticated/profile_/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile_/wallet': typeof AuthenticatedProfileWalletRoute
  '/api/public/qi-webhook': typeof ApiPublicQiWebhookRoute
  '/_authenticated/profile_/wallet_/statement': typeof AuthenticatedProfileWalletStatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brands'
    | '/bundles'
    | '/cart'
    | '/categories'
    | '/deals'
    | '/expiring'
    | '/featured'
    | '/how-discounts'
    | '/new'
    | '/notifications'
    | '/offers'
    | '/outlet'
    | '/products'
    | '/rewards'
    | '/scan'
    | '/search'
    | '/vendor-signup'
    | '/vendors'
    | '/brand'
    | '/orders'
    | '/profile'
    | '/savings'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipping'
    | '/admin/vendors'
    | '/bundle/$id'
    | '/payment/$orderId'
    | '/product/$id'
    | '/vendor/$slug'
    | '/admin/'
    | '/orders/$id'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/wallet'
    | '/api/public/qi-webhook'
    | '/profile/wallet/statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brands'
    | '/bundles'
    | '/cart'
    | '/categories'
    | '/deals'
    | '/expiring'
    | '/featured'
    | '/how-discounts'
    | '/new'
    | '/notifications'
    | '/offers'
    | '/outlet'
    | '/products'
    | '/rewards'
    | '/scan'
    | '/search'
    | '/vendor-signup'
    | '/vendors'
    | '/brand'
    | '/orders'
    | '/profile'
    | '/savings'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipping'
    | '/admin/vendors'
    | '/bundle/$id'
    | '/payment/$orderId'
    | '/product/$id'
    | '/vendor/$slug'
    | '/admin'
    | '/orders/$id'
    | '/profile/addresses'
    | '/profile/edit'
    | '/profile/wallet'
    | '/api/public/qi-webhook'
    | '/profile/wallet/statement'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/brands'
    | '/bundles'
    | '/cart'
    | '/categories'
    | '/deals'
    | '/expiring'
    | '/featured'
    | '/how-discounts'
    | '/new'
    | '/notifications'
    | '/offers'
    | '/outlet'
    | '/products'
    | '/rewards'
    | '/scan'
    | '/search'
    | '/vendor-signup'
    | '/vendors'
    | '/_authenticated/brand'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/savings'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipping'
    | '/admin/vendors'
    | '/bundle/$id'
    | '/payment/$orderId'
    | '/product/$id'
    | '/vendor/$slug'
    | '/admin/'
    | '/_authenticated/orders_/$id'
    | '/_authenticated/profile_/addresses'
    | '/_authenticated/profile_/edit'
    | '/_authenticated/profile_/wallet'
    | '/api/public/qi-webhook'
    | '/_authenticated/profile_/wallet_/statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  BundlesRoute: typeof BundlesRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  DealsRoute: typeof DealsRoute
  ExpiringRoute: typeof ExpiringRoute
  FeaturedRoute: typeof FeaturedRoute
  HowDiscountsRoute: typeof HowDiscountsRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OutletRoute: typeof OutletRoute
  ProductsRoute: typeof ProductsRoute
  RewardsRoute: typeof RewardsRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  VendorSignupRoute: typeof VendorSignupRoute
  VendorsRoute: typeof VendorsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  BundleIdRoute: typeof BundleIdRoute
  PaymentOrderIdRoute: typeof PaymentOrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  VendorSlugRoute: typeof VendorSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicQiWebhookRoute: typeof ApiPublicQiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiring': {
      id: '/expiring'
      path: '/expiring'
      fullPath: '/expiring'
      preLoaderRoute: typeof ExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-discounts': {
      id: '/how-discounts'
      path: '/how-discounts'
      fullPath: '/how-discounts'
      preLoaderRoute: typeof HowDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-signup': {
      id: '/vendor-signup'
      path: '/vendor-signup'
      fullPath: '/vendor-signup'
      preLoaderRoute: typeof VendorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brand': {
      id: '/_authenticated/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedBrandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/savings': {
      id: '/_authenticated/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AuthenticatedSavingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$id': {
      id: '/bundle/$id'
      path: '/bundle/$id'
      fullPath: '/bundle/$id'
      preLoaderRoute: typeof BundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$orderId': {
      id: '/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof PaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$slug': {
      id: '/vendor/$slug'
      path: '/vendor/$slug'
      fullPath: '/vendor/$slug'
      preLoaderRoute: typeof VendorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders_/$id': {
      id: '/_authenticated/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/addresses': {
      id: '/_authenticated/profile_/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof AuthenticatedProfileAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/edit': {
      id: '/_authenticated/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile_/wallet': {
      id: '/_authenticated/profile_/wallet'
      path: '/profile/wallet'
      fullPath: '/profile/wallet'
      preLoaderRoute: typeof AuthenticatedProfileWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/qi-webhook': {
      id: '/api/public/qi-webhook'
      path: '/api/public/qi-webhook'
      fullPath: '/api/public/qi-webhook'
      preLoaderRoute: typeof ApiPublicQiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile_/wallet_/statement': {
      id: '/_authenticated/profile_/wallet_/statement'
      path: '/profile/wallet/statement'
      fullPath: '/profile/wallet/statement'
      preLoaderRoute: typeof AuthenticatedProfileWalletStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandRoute: typeof AuthenticatedBrandRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavingsRoute: typeof AuthenticatedSavingsRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedProfileAddressesRoute: typeof AuthenticatedProfileAddressesRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileWalletRoute: typeof AuthenticatedProfileWalletRoute
  AuthenticatedProfileWalletStatementRoute: typeof AuthenticatedProfileWalletStatementRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandRoute: AuthenticatedBrandRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavingsRoute: AuthenticatedSavingsRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedProfileAddressesRoute: AuthenticatedProfileAddressesRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileWalletRoute: AuthenticatedProfileWalletRoute,
  AuthenticatedProfileWalletStatementRoute:
    AuthenticatedProfileWalletStatementRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  BundlesRoute: BundlesRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  DealsRoute: DealsRoute,
  ExpiringRoute: ExpiringRoute,
  FeaturedRoute: FeaturedRoute,
  HowDiscountsRoute: HowDiscountsRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OutletRoute: OutletRoute,
  ProductsRoute: ProductsRoute,
  RewardsRoute: RewardsRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  VendorSignupRoute: VendorSignupRoute,
  VendorsRoute: VendorsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  BundleIdRoute: BundleIdRoute,
  PaymentOrderIdRoute: PaymentOrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  VendorSlugRoute: VendorSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicQiWebhookRoute: ApiPublicQiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
