ALTER TABLE public.store_settings
  ADD COLUMN IF NOT EXISTS site_name_ar text NOT NULL DEFAULT 'دنتال ستور',
  ADD COLUMN IF NOT EXISTS site_name_ku text NOT NULL DEFAULT 'دەنتاڵ ستۆر',
  ADD COLUMN IF NOT EXISTS tagline_ar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tagline_ku text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_title_ar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_title_ku text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_description_ar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_description_ku text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS logo_url text,
  ADD COLUMN IF NOT EXISTS favicon_url text,
  ADD COLUMN IF NOT EXISTS og_image_url text,
  ADD COLUMN IF NOT EXISTS logo_emoji text NOT NULL DEFAULT '🦷',
  ADD COLUMN IF NOT EXISTS contact_phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS whatsapp text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_email text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_ar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_ku text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS facebook_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS telegram_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS default_lang text NOT NULL DEFAULT 'ar',
  ADD COLUMN IF NOT EXISTS currency_ar text NOT NULL DEFAULT 'د.ع',
  ADD COLUMN IF NOT EXISTS currency_ku text NOT NULL DEFAULT 'د.ع',
  ADD COLUMN IF NOT EXISTS min_order_total numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_fee numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS free_delivery_over numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS announcement_ar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS announcement_ku text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS show_announcement boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS maintenance_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS maintenance_note_ar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS maintenance_note_ku text NOT NULL DEFAULT '';